CREATE TABLE IF NOT EXISTS servers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  base_url VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  server_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  path VARCHAR(500) NOT NULL DEFAULT '/',
  method ENUM('GET','POST','PUT','DELETE','PATCH') DEFAULT 'GET',
  headers JSON DEFAULT NULL,
  body TEXT DEFAULT NULL,
  execute_interval_sec INT DEFAULT 60,
  error_interval_sec INT DEFAULT 30,
  response_timeout_ms INT DEFAULT 5000,
  is_active TINYINT(1) DEFAULT 1,
  last_executed_at TIMESTAMP NULL DEFAULT NULL,
  next_execution_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT NOT NULL,
  server_id INT NOT NULL,
  status ENUM('success','error') NOT NULL,
  title VARCHAR(255) DEFAULT NULL,
  server_name VARCHAR(255) DEFAULT NULL,
  base_url VARCHAR(500) DEFAULT NULL,
  path VARCHAR(500) DEFAULT NULL,
  method VARCHAR(10) DEFAULT NULL,
  http_code INT DEFAULT NULL,
  response_body LONGTEXT DEFAULT NULL,
  response_time_ms INT DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('timezone', 'Asia/Jakarta');

CREATE INDEX idx_next_execution ON tasks(next_execution_at, is_active);
CREATE INDEX idx_logs_executed_at ON logs(executed_at DESC);
CREATE INDEX idx_logs_task_id ON logs(task_id);
CREATE INDEX idx_logs_status ON logs(status);
